version: "3.0"
services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/app-frontend
      - /app-frontend/node_modules
    env_file:
      - ./.env

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "mysql://root:password@mysql:3306/my_database"
    depends_on:
      mysql:
        condition: service_healthy
    command: ["sh", "-c", "npx prisma db push --force-reset && npm run seed && npm run dev"]
    volumes:
      - ./backend:/app-backend
      - /app-backend/node_modules
    env_file:
      - ./.env

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  mysql_data:
